name: CI

on:
  push:
    branches: [ main, 'feature/**', 'fdd/**' ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    name: Frontend build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install frontend deps
        run: npm ci
      - name: Typecheck
        run: npm run typecheck
      - name: Build frontend
        run: npm run build
      - name: Run frontend tests
        run: npm test -- --coverage --coverageDirectory=coverage/frontend
      - name: Upload frontend coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-frontend
          path: coverage/frontend

  backend:
    name: Backend build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install backend deps
        working-directory: backend
        run: npm ci
      - name: Build backend
        working-directory: backend
        run: npm run build
      - name: Run backend tests
        working-directory: backend
        run: npm test -- --coverage --coverageDirectory=coverage/backend
      - name: Upload backend coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-backend
          path: backend/coverage
  # optional-docker job removed to avoid running Docker builds in CI for now